services:
  nginx:
    image: nginx:latest
    container_name: rinhaneto10-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinhaneto10
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"
          
  rinhaneto10:
    image: rinhaneto10
    container_name: rinhaneto10
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080'
      - INSTANCE_ID=API-1
      - WORKER_CONCURRENCY=16
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "110MB"
          
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true